# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rirBXqeWJnSjIdSsuIvBAyXRBoJXhAlQ
"""

pip install psutil

import platform
import psutil

def get_os_info():
    os_info = {
        'OS': platform.system(),
        'OS Version': platform.version(),
        'Release': platform.release(),
        'Architecture': platform.architecture()[0]
    }
    return os_info

def get_kernel_info():
    kernel_info = {
        'Kernel Version': platform.uname().version,
        'Machine': platform.machine(),
        'Node Name': platform.node(),
        'Processor': platform.processor()
    }
    return kernel_info

def get_hardware_info():
    try:
        cpu_freq = psutil.cpu_freq()
        cpu_info = {
            'CPU Cores': psutil.cpu_count(logical=False),
            'Logical CPUs': psutil.cpu_count(logical=True),
            'CPU Frequency': f"{cpu_freq.current} MHz" if cpu_freq else "N/A",
            'Total RAM': f"{round(psutil.virtual_memory().total / (1024 ** 3))} GB"
        }

        disk_info = psutil.disk_usage('/')
        disk_info_dict = {
            'Total Disk Space': f"{round(disk_info.total / (1024 ** 3))} GB",
            'Used Disk Space': f"{round(disk_info.used / (1024 ** 3))} GB",
            'Free Disk Space': f"{round(disk_info.free / (1024 ** 3))} GB"
        }

        return cpu_info, disk_info_dict
    except Exception as e:
        print(f"Error getting hardware info: {e}")
        return {}, {}

def main():
    try:
        print("Operating System Information:")
        os_info = get_os_info()
        for key, value in os_info.items():
            print(f"{key}: {value}")

        print("\nKernel Information:")
        kernel_info = get_kernel_info()
        for key, value in kernel_info.items():
            print(f"{key}: {value}")

        print("\nHardware Information:")
        cpu_info, disk_info = get_hardware_info()
        if cpu_info:
            for key, value in cpu_info.items():
                print(f"{key}: {value}")
        if disk_info:
            for key, value in disk_info.items():
                print(f"{key}: {value}")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()